//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analize_pacienti
    {
        public int Analize_pacientiID { get; set; }
        public Nullable<int> Pacient_ID { get; set; }
        public Nullable<int> Analiza_ID { get; set; }
        public string Rezultat { get; set; }
    
        public virtual Analize Analize { get; set; }
        public virtual Utilizatori Utilizatori { get; set; }
    }
}
