//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programari
    {
        public int ProgramareID { get; set; }
        public Nullable<int> MedicID { get; set; }
        public Nullable<int> PacientID { get; set; }
        public string DataProgramare { get; set; }
        public string OraProgramare { get; set; }
    
        public virtual Utilizatori Utilizatori { get; set; }
        public virtual Utilizatori Utilizatori1 { get; set; }
    }
}
